import { describe, expect, it } from 'vitest'

import {
  parseAIGenerationHistory,
  parseAIChatSessionDetail,
  parseAIChatTurnResponse,
  parseGenerateStyleSpecResponse,
  parseRunnerJob,
} from './normalize'

describe('parseRunnerJob', () => {
  it('accepts host integration payload with launch_method', () => {
    const parsed = parseRunnerJob({
      job_id: 'job_1',
      job_type: 'compile_captureone',
      status: 'succeeded',
      payload: {
        style_id: 'style_1',
        version: 'v1',
        execution_mode: 'host',
      },
      result: {
        artifact_id: 'artifact_1',
        sha256: 'abc123',
        download_url: '/artifacts/artifact_1',
        host_integration: {
          mode: 'host',
          launch_method: 'cli',
          captureone_app_path: '/Applications/Capture One.app',
          imported_costyle_path: '/tmp/artifact_1.costyle',
        },
      },
      error: null,
    })

    expect(parsed.result?.host_integration?.launch_method).toBe('cli')
  })

  it('rejects invalid host integration launch_method', () => {
    expect(() =>
      parseRunnerJob({
        job_id: 'job_1',
        job_type: 'compile_captureone',
        status: 'failed',
        payload: {
          style_id: 'style_1',
          version: 'v1',
          execution_mode: 'host',
        },
        result: {
          host_integration: {
            mode: 'host',
            launch_method: 'manual',
            error_code: 'APPLE_EVENT_DENIED',
            error_message: 'blocked',
          },
        },
        error: 'blocked',
      }),
    ).toThrow('Invalid runner job payload')
  })

  it('rejects invalid host integration error_code', () => {
    expect(() =>
      parseRunnerJob({
        job_id: 'job_1',
        job_type: 'compile_captureone',
        status: 'failed',
        payload: {
          style_id: 'style_1',
          version: 'v1',
          execution_mode: 'host',
        },
        result: {
          host_integration: {
            mode: 'host',
            launch_method: 'open',
            error_code: 'SOMETHING_ELSE',
            error_message: 'blocked',
          },
        },
        error: 'blocked',
      }),
    ).toThrow('Invalid runner job payload')
  })
})

describe('parseGenerateStyleSpecResponse', () => {
  it('accepts valid ai generation payload', () => {
    const parsed = parseGenerateStyleSpecResponse({
      style_spec: {
        name: 'Warm Cinematic Portrait',
        intent: ['warm', 'cinematic'],
        captureone: {
          keys: {
            Exposure: 0.1,
            Contrast: 7,
          },
          notes: 'Generated by AI',
        },
        safe: {
          remove_lens_light_falloff: true,
          remove_white_balance: true,
          remove_exposure: false,
        },
      },
      rationale: 'Prompt interpreted with warm cinematic intent.',
      warnings: [],
      provider: 'ollama',
      model: 'llama3.1:8b',
      generation_ms: 24,
      fallback_used: false,
    })

    expect(parsed.provider).toBe('ollama')
    expect(parsed.style_spec.captureone.keys.Contrast).toBe(7)
  })

  it('rejects invalid ai payload', () => {
    expect(() =>
      parseGenerateStyleSpecResponse({
        style_spec: {
          name: '',
        },
        warnings: ['x'],
        provider: 'mock',
        model: 'mock-v1',
      }),
    ).toThrow('Invalid AI generate response payload')
  })

  it('rejects invalid telemetry fields', () => {
    expect(() =>
      parseGenerateStyleSpecResponse({
        style_spec: {
          name: 'AI',
          intent: ['warm'],
          captureone: {
            keys: { Exposure: 0.1 },
          },
        },
        warnings: [],
        provider: 'mock',
        model: 'mock-v1',
        generation_ms: 'fast',
      }),
    ).toThrow('Invalid AI generate response payload')
  })
})

describe('parseAIGenerationHistory', () => {
  it('accepts valid ai history payload', () => {
    const parsed = parseAIGenerationHistory([
      {
        generation_id: 'gen_1',
        created_at: '2026-03-01T10:00:00Z',
        client_key: '127.0.0.1',
        prompt: 'warm portrait',
        target: 'captureone',
        style_spec: {
          name: 'AI Warm',
          intent: ['warm'],
          captureone: {
            keys: { Exposure: 0.1 },
          },
        },
        warnings: [],
        provider: 'mock',
        model: 'mock-v1',
      },
    ])

    expect(parsed).toHaveLength(1)
    expect(parsed[0]?.generation_id).toBe('gen_1')
  })

  it('rejects invalid ai history payload', () => {
    expect(() =>
      parseAIGenerationHistory([
        {
          generation_id: 'gen_1',
          created_at: '2026-03-01T10:00:00Z',
          target: 'captureone',
        },
      ]),
    ).toThrow('Invalid AI generation history payload')
  })
})

describe('parseAIChat payloads', () => {
  const session = {
    session_id: 'sess_1',
    title: 'Session',
    status: 'active',
    style_spec: {
      name: 'Base',
      intent: ['portrait'],
      captureone: {
        keys: { Exposure: 0.1, Contrast: 4 },
      },
      safe: {
        remove_lens_light_falloff: true,
        remove_white_balance: true,
        remove_exposure: false,
      },
    },
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-01T00:00:10Z',
  }

  const turn = {
    turn_id: 'turn_1',
    session_id: 'sess_1',
    user_message: 'add contrast',
    assistant_message: 'I prepared updates.',
    proposed_changes: [{ key: 'Contrast', from_value: 4, to_value: 8 }],
    warnings: [],
    guidance: {
      detected_goals: ['contrast_tuning'],
      reasoning_summary: 'Detected contrast goal.',
      suggested_next_messages: ['reduce highlights'],
    },
    applied: false,
    created_at: '2026-03-01T00:00:12Z',
  }

  it('accepts valid chat turn response', () => {
    const parsed = parseAIChatTurnResponse({
      session,
      turn,
    })
    expect(parsed.turn.turn_id).toBe('turn_1')
  })

  it('accepts valid chat session detail', () => {
    const parsed = parseAIChatSessionDetail({
      session,
      turns: [turn],
    })
    expect(parsed.turns).toHaveLength(1)
  })
})
